const ACTION_PREFIX = '@LIVE_SEARCH/';
export const SET_SEARCH_TERM = `${ACTION_PREFIX}SET_SEARCH_TERM`;
export const SET_SEARCH_RESULTS = `${ACTION_PREFIX}SET_SEARCH_RESULTS`;
export const FETCH_RESULTS = `${ACTION_PREFIX}FETCH_RESULTS`;
