const ACTION_PREFIX = '@UI/';
export const TOGGLE_SEARCH = `${ACTION_PREFIX}TOGGLE_SEARCH`;
export const TOGGLE_MENU = `${ACTION_PREFIX}TOGGLE_MENU`;
export const TOGGLE_BASKET = `${ACTION_PREFIX}TOGGLE_BASKET`;
export const SET_DEVICE_TYPE = `${ACTION_PREFIX}SET_DEVICE_TYPE`;
export const SET_SCREEN_SIZE = `${ACTION_PREFIX}SET_SCREEN_SIZE`;
export const BROWSER_RESIZE = `${ACTION_PREFIX}BROWSER_RESIZE`;
export const HAS_DROPDOWN_FILTERS_SELECTED = `${ACTION_PREFIX}HAS_DROPDOWN_FILTERS_SELECTED`;
