const ACTION_PREFIX = '@UI/';
export const TOGGLE_SEARCH = `${ACTION_PREFIX}TOGGLE_SEARCH`;
export const TOGGLE_MOBILE_MENU = `${ACTION_PREFIX}TOGGLE_MOBILE_MENU`;
export const SET_DEVICE_TYPE = `${ACTION_PREFIX}SET_DEVICE_TYPE`;
export const SET_SCREEN_SIZE = `${ACTION_PREFIX}SET_SCREEN_SIZE`;
export const BROWSER_RESIZE = `${ACTION_PREFIX}BROWSER_RESIZE`;
export const TOGGLE_DOCS_SIDEBAR = `${ACTION_PREFIX}TOGGLE_DOCS_SIDEBAR`;
