const ACTION_PREFIX = '@BASKET/';
export const ADD_TO_BASKET = `${ACTION_PREFIX}ADD_TO_BASKET`;
export const REMOVE_FROM_BASKET = `${ACTION_PREFIX}REMOVE_FROM_BASKET`;
export const UPDATE_QUANTITY = `${ACTION_PREFIX}UPDATE_QUANTITY`;
export const UPDATE_MATCHING_PRODUCTS = `${ACTION_PREFIX}UPDATE_MATCHING_PRODUCTS`;
export const INITIALISED_BASKET = `${ACTION_PREFIX}INITIALISED_BASKET`;
