name: Docker - Tag and push release

# Controls when the workflow will run
on:
  # Triggers the workflow only on a release-* tag
  push:
    tags:
      - 'release-*' # Push events to matching release-*, i.e. release-v1.0.0

env:
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  APP_IMAGE: ghcr.io/${{ github.repository }}/master/app

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Login against a Docker registry except on PR
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull latest image, tag release and push
        run: |
          docker pull ${{ env.APP_IMAGE }}:latest || true
          docker tag ${{ env.APP_IMAGE }}:latest ${{ env.APP_IMAGE }}:release
          docker push ${{ env.APP_IMAGE }}:release
          docker tag ${{ env.APP_IMAGE }}:latest ${{ env.APP_IMAGE }}:${{ github.ref_name }}
          docker push ${{ env.APP_IMAGE }}:${{ github.ref_name }}
